<?php
/**
 * AccountReadFullResourcesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountReadFullResourcesTest Class Doc Comment
 *
 * @category    Class
 * @description AccountReadFullResources
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountReadFullResourcesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountReadFullResources"
     */
    public function testAccountReadFullResources()
    {
    }

    /**
     * Test attribute "contractorId"
     */
    public function testPropertyContractorId()
    {
    }

    /**
     * Test attribute "contractorName"
     */
    public function testPropertyContractorName()
    {
    }

    /**
     * Test attribute "contractorPhone"
     */
    public function testPropertyContractorPhone()
    {
    }

    /**
     * Test attribute "contractorOptIn"
     */
    public function testPropertyContractorOptIn()
    {
    }

    /**
     * Test attribute "jobsUrl"
     */
    public function testPropertyJobsUrl()
    {
    }

    /**
     * Test attribute "productsUrl"
     */
    public function testPropertyProductsUrl()
    {
    }

    /**
     * Test attribute "mapUrl"
     */
    public function testPropertyMapUrl()
    {
    }

    /**
     * Test attribute "vehiclesUrl"
     */
    public function testPropertyVehiclesUrl()
    {
    }
}
