<?php
/**
 * JobVehicleSummaryDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JobVehicleSummaryDataTest Class Doc Comment
 *
 * @category    Class
 * @description JobVehicleSummaryData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobVehicleSummaryDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JobVehicleSummaryData"
     */
    public function testJobVehicleSummaryData()
    {
    }

    /**
     * Test attribute "vehicle"
     */
    public function testPropertyVehicle()
    {
    }

    /**
     * Test attribute "timeTaken"
     */
    public function testPropertyTimeTaken()
    {
    }

    /**
     * Test attribute "timeWorking"
     */
    public function testPropertyTimeWorking()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "distanceWorking"
     */
    public function testPropertyDistanceWorking()
    {
    }

    /**
     * Test attribute "distanceNotWorking"
     */
    public function testPropertyDistanceNotWorking()
    {
    }
}
