<?php
/**
 * JobWriteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JobWriteTest Class Doc Comment
 *
 * @category    Class
 * @description JobWrite
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobWriteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JobWrite"
     */
    public function testJobWrite()
    {
    }

    /**
     * Test attribute "geometry"
     */
    public function testPropertyGeometry()
    {
    }

    /**
     * Test attribute "productRates"
     */
    public function testPropertyProductRates()
    {
    }

    /**
     * Test attribute "customerId"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "contractorId"
     */
    public function testPropertyContractorId()
    {
    }

    /**
     * Test attribute "customerName"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "originSupplier"
     */
    public function testPropertyOriginSupplier()
    {
    }

    /**
     * Test attribute "originReference"
     */
    public function testPropertyOriginReference()
    {
    }

    /**
     * Test attribute "orderSubtypeId"
     */
    public function testPropertyOrderSubtypeId()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "dueDate2"
     */
    public function testPropertyDueDate2()
    {
    }

    /**
     * Test attribute "waterRate"
     */
    public function testPropertyWaterRate()
    {
    }

    /**
     * Test attribute "tankSize"
     */
    public function testPropertyTankSize()
    {
    }
}
