<?php
/**
 * ProductChemistryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductChemistryTest Class Doc Comment
 *
 * @category    Class
 * @description ProductChemistry
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductChemistryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductChemistry"
     */
    public function testProductChemistry()
    {
    }

    /**
     * Test attribute "nitrogen"
     */
    public function testPropertyNitrogen()
    {
    }

    /**
     * Test attribute "phosphorus"
     */
    public function testPropertyPhosphorus()
    {
    }

    /**
     * Test attribute "potassium"
     */
    public function testPropertyPotassium()
    {
    }

    /**
     * Test attribute "calcium"
     */
    public function testPropertyCalcium()
    {
    }
}
