<?php
/**
 * AppApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AppApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdReportOptions
     *
     * Returns information about whether reports can be requested for the given job..
     *
     */
    public function testAccountsAccountIdJobsJobIdReportOptions()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdReportPost
     *
     * Request a contractor report be sent to a specified email address..
     *
     */
    public function testAccountsAccountIdJobsJobIdReportPost()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersGeoFeatureIdDelete
     *
     * Delete a marker from the map..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersGeoFeatureIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersGeoFeatureIdPatch
     *
     * Update details of a marker..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersGeoFeatureIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersPost
     *
     * Create a new marker in the given map. The response body contains the identifier of the created feature..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersPost()
    {
    }

    /**
     * Test case for accountsByUserGet
     *
     * List accounts available to the user..
     *
     */
    public function testAccountsByUserGet()
    {
    }

    /**
     * Test case for mobileUserAccessUserPhonePost
     *
     * Retrieve mobile app access token..
     *
     */
    public function testMobileUserAccessUserPhonePost()
    {
    }

    /**
     * Test case for mobileUserNotificationsGet
     *
     * Retrieve notifications previously issued for this user..
     *
     */
    public function testMobileUserNotificationsGet()
    {
    }

    /**
     * Test case for mobileUserNotificationsNotificationTokenDelete
     *
     * Delete a push notification token..
     *
     */
    public function testMobileUserNotificationsNotificationTokenDelete()
    {
    }

    /**
     * Test case for mobileUserNotificationsNotificationTokenPost
     *
     * Register or refresh a push notification token..
     *
     */
    public function testMobileUserNotificationsNotificationTokenPost()
    {
    }
}
