<?php
/**
 * JobApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * JobApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsAccountIdJobsGdxJobIdGet
     *
     * Detailed information about a particular job returned in GDX format..
     *
     */
    public function testAccountsAccountIdJobsGdxJobIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsGet
     *
     * Information about all available jobs, optionally filtered, ordered by last modification date (desc)..
     *
     */
    public function testAccountsAccountIdJobsGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdAssignPost
     *
     * Assign a job to one or more devices..
     *
     */
    public function testAccountsAccountIdJobsJobIdAssignPost()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdDelete
     *
     * Delete a particular job..
     *
     */
    public function testAccountsAccountIdJobsJobIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdDiagnosticPost
     *
     * Send diagnostics about a job..
     *
     */
    public function testAccountsAccountIdJobsJobIdDiagnosticPost()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdGeometryNonworkedDetailedGet
     *
     * Get a job's non-worked geometry as placement lines including rates, altitudes, and timestamps..
     *
     */
    public function testAccountsAccountIdJobsJobIdGeometryNonworkedDetailedGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdGeometryRequestedGet
     *
     * Get a job's requested (planned) geometry as a set of polygons and centre lines if available..
     *
     */
    public function testAccountsAccountIdJobsJobIdGeometryRequestedGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdGeometryWorkedDetailedGet
     *
     * Get a job's worked geometry as placement lines including rates, altitudes, and timestamps..
     *
     */
    public function testAccountsAccountIdJobsJobIdGeometryWorkedDetailedGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdGeometryWorkedGet
     *
     * Get a job's worked geometry as series of placement polygons..
     *
     */
    public function testAccountsAccountIdJobsJobIdGeometryWorkedGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdGet
     *
     * Retrieve information about a specific job..
     *
     */
    public function testAccountsAccountIdJobsJobIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdPatch
     *
     * Modify an existing job..
     *
     */
    public function testAccountsAccountIdJobsJobIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdReportOptions
     *
     * Returns information about whether reports can be requested for the given job..
     *
     */
    public function testAccountsAccountIdJobsJobIdReportOptions()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdReportPost
     *
     * Request a contractor report be sent to a specified email address..
     *
     */
    public function testAccountsAccountIdJobsJobIdReportPost()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdVehicleSummaryDaysGet
     *
     * Get a job's usage summary data by vehicle..
     *
     */
    public function testAccountsAccountIdJobsJobIdVehicleSummaryDaysGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdVehicleSummaryGet
     *
     * Get a job's usage summary data by vehicle..
     *
     */
    public function testAccountsAccountIdJobsJobIdVehicleSummaryGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsJobIdYieldGet
     *
     * Get a job's geospatial yield data..
     *
     */
    public function testAccountsAccountIdJobsJobIdYieldGet()
    {
    }

    /**
     * Test case for accountsAccountIdJobsPost
     *
     * Create a new job..
     *
     */
    public function testAccountsAccountIdJobsPost()
    {
    }

    /**
     * Test case for directJobPost
     *
     * Create a new job..
     *
     */
    public function testDirectJobPost()
    {
    }
}
