<?php
/**
 * MapApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MapApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MapApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsAccountIdMapsGet
     *
     * List of all available maps..
     *
     */
    public function testAccountsAccountIdMapsGet()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdDelete
     *
     * Delete a particular map..
     *
     */
    public function testAccountsAccountIdMapsMapIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdGeometryGet
     *
     * Get a map's geometry information..
     *
     */
    public function testAccountsAccountIdMapsMapIdGeometryGet()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdGet
     *
     * Detailed information about a particular map..
     *
     */
    public function testAccountsAccountIdMapsMapIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersGeoFeatureIdDelete
     *
     * Delete a marker from the map..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersGeoFeatureIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersGeoFeatureIdPatch
     *
     * Update details of a marker..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersGeoFeatureIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdMarkersPost
     *
     * Create a new marker in the given map. The response body contains the identifier of the created feature..
     *
     */
    public function testAccountsAccountIdMapsMapIdMarkersPost()
    {
    }

    /**
     * Test case for accountsAccountIdMapsMapIdPatch
     *
     * Update an existing map..
     *
     */
    public function testAccountsAccountIdMapsMapIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdMapsPost
     *
     * Create a new map..
     *
     */
    public function testAccountsAccountIdMapsPost()
    {
    }
}
