<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TracMap API
 *
 * The TracMap API allows you to create and manage __Jobs__, __Products__, and __Maps__ on TracMap Online.
 *
 * OpenAPI spec version: 1.0.25
 * Contact: api@tracmap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.42-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsAccountIdProductsGet
     *
     * Information about all available products, optionally filtered..
     *
     */
    public function testAccountsAccountIdProductsGet()
    {
    }

    /**
     * Test case for accountsAccountIdProductsPost
     *
     * Create a new custom product..
     *
     */
    public function testAccountsAccountIdProductsPost()
    {
    }

    /**
     * Test case for accountsAccountIdProductsProductIdDelete
     *
     * Delete a particular product..
     *
     */
    public function testAccountsAccountIdProductsProductIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdProductsProductIdGet
     *
     * Detailed information about a particular product..
     *
     */
    public function testAccountsAccountIdProductsProductIdGet()
    {
    }

    /**
     * Test case for directProductGet
     *
     * Information about all available products, optionally filtered. Only used in conjuction with /direct/job..
     *
     */
    public function testDirectProductGet()
    {
    }
}
